### ISSUE TITLE
Entry level PPD and CCDs?

### ISSUE THREAD

**Issue by utsengar** [travishathaway/python-ach#4]
PPD and CCD can be added at the batch level:

```
    self.ach_file.add_batch('CCD',entries,credits=False)
```

but as per the ACH spec, it can also be added at the entry level.
So can something like this be done?

```
        dbt_entry =  {  'type' : '27',
                        'routing_number' : str(dbt_user_bank.routing_number),
                        'account_number' : str(dbt_user_bank.account_number),
                        'amount' : tx.amount,
                        'name' : dbt_user.name, 
                        'trace_num': tx.transaction_id,
                        'std_ent_cls_code': 'CCD'}
```

How easy/hard will it be in the current version of python-ach? Any pointers

I am trying to add multiple CCD and PPD type transactions (aka entries) in a single batch.

**Comment by utkarsh2012** [comment]
@sankaet No it didn't, I am working on a fix
